# Generated by Django 2.1.1 on 2018-10-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases', models.CharField(choices=[('Cholera', 'CHOLERA'), ('HIV', 'HIV'), ('Malaria', 'MALARIA'), ('Typhoid', 'TYPHOID'), ('Measles', 'MEASLES')], default='Malaria', max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='Male', max_length=19)),
            ],
        ),
        migrations.AddField(
            model_name='diseases',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkmate.Gender'),
        ),
    ]
