# Generated by Django 2.1.1 on 2018-10-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkmate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseases',
            old_name='gender',
            new_name='gender_disease',
        ),
    ]
